[build]
  publish = "dist/public"
  command = "vite build && cd netlify/functions && npm install"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"

# API redirects for serverless functions
[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200

[[redirects]]
  from = "/api/referral"
  to = "/.netlify/functions/referral"
  status = 200

[[redirects]]
  from = "/api/buttons"
  to = "/.netlify/functions/buttons"
  status = 200

[[redirects]]
  from = "/api/buttons/:number"
  to = "/.netlify/functions/buttons-delete/:number"
  status = 200

[[redirects]]
  from = "/api/debug"
  to = "/.netlify/functions/debug"
  status = 200

[[redirects]]
  from = "/api/test-db"
  to = "/.netlify/functions/test-db"
  status = 200

# SPA fallback - this should be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200